  ####################################################################
  # INFRASTRUCTURE CREATION (UNCOMMENT THIS SECTION WHEN DEPLOYING)
  ####################################################################
name: Deploy lumifi backend Infrastructure to production environment

on:
  push:
    branches:
      - production-test

permissions:
  contents: read
  id-token: write

jobs:
  aws-resources-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-infra
    env:
      ENVIRONMENT: prod
      AWS_REGION: us-east-1
    outputs:
      db_host: ${{ steps.set-db-outputs.outputs.db_host }}
      db_port: ${{ steps.set-db-outputs.outputs.db_port }}

      lambda_sg_id: ${{ steps.set-vpc-outputs.outputs.lambda_sg_id }}
      subnet_ids: ${{ steps.set-vpc-outputs.outputs.subnet_ids }}
      rds_type: ${{ steps.set-db-outputs.outputs.rds_type }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          # echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      # Deploy Terraform infrastructure
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Select/Create Workspace
        run: |
          terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT

      - name: Terraform Validate
        run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan -out=tfplan

      - name: Terraform Plan with Private RDS
        run: terraform plan -out=tfplan -var="environment=prod" -var="deploy_public_rds=false" -var="deploy_private_rds=true"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform output
        run: |
          LAMBDA_SG_ID=$(terraform output -raw lambda_sg_id)
          echo "Lambda sg: $LAMBDA_SG_ID"
          echo "LAMBDA_SG_ID=$LAMBDA_SG_ID" >> db_outputs.env

          SUBNET_IDS=$(terraform output -raw subnet_ids)
          echo "Subnet id: $SUBNET_IDS"
          echo "SUBNET_IDS=$SUBNET_IDS" >> db_outputs.env

      # Get and parse RDS endpoint seperate endpoint & port
      - name: Get and Parse RDS Endpoint
        id: set-db-outputs
        run: |
          # DB_ENDPOINT_FULL=$(terraform output -raw rds_endpoint)
          # echo "Full RDS Endpoint: $DB_ENDPOINT_FULL"
          DB_ENDPOINT_FULL=$(terraform output -raw rds_endpoint)
          RDS_TYPE=$(terraform output -raw rds_type)
          echo "Full RDS Endpoint: $DB_ENDPOINT_FULL"
          echo "RDS Type: $RDS_TYPE"

          # Extract host and port
          DB_HOST=$(echo "$DB_ENDPOINT_FULL" | cut -d ':' -f 1)
          DB_PORT=$(echo "$DB_ENDPOINT_FULL" | cut -d ':' -f 2)

          # Create outputs file in the working directory
          echo "DB_HOST=$DB_HOST" >> db_outputs.env
          echo "DB_PORT=$DB_PORT" >> db_outputs.env
          

          # Mask values in logs
          echo "::add-mask::$DB_HOST"
          echo "::add-mask::$DB_PORT"

      - name: Upload DB outputs
        uses: actions/upload-artifact@v4
        with:
          name: db-env-vars
          path: backend-infra/db_outputs.env # Correct path to file